MinDoc_New:
  image: registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc:v1.0
  privileged: false
  restart: always
  ports:
    - 8181:8181
  volumes:
    - /data/mindoc/database:/mindoc/database
    - /data/mindoc/uploads:/mindoc/uploads
  environment:
    # - MINDOC_RUN_MODE=prod
    # - MINDOC_DB_ADAPTER=sqlite3
    # - MINDOC_DB_DATABASE=./database/mindoc.db
    - MINDOC_CACHE=false
    # - MINDOC_CACHE_PROVIDER=file
    - MINDOC_ENABLE_EXPORT=false
    - MINDOC_BASE_URL=http://soluty.xyz
